#! /bin/bash

url="http://localhost:8080/story/$1/$2"

echo url: $url

curl -X POST \
	--user hallo:welt \
	--header "Content-Type: application/json" \
	--cookie cookies.txt \
	--data "{\"title\": \"$3\", \"content\": \"$4\", \"created\": \"2014-01-15T11:22:33.444+01\", \"createdBy\": \"nobody\", \"tags\": [\"$5\"] }" \
	$url

echo 
