#! /bin/bash

if [ $# -lt 2 ]
  then
    echo "amanuensis <command> <heroku-app | local>";
    exit
fi

script=$1
app=$2

shift 2

if [ $app = "local" ]
  then
    graphenedb="http://localhost:7474"
    elasticsearch="http://localhost:9200"
  else
    graphenedb=`heroku config --app $app | grep GRAPHENEDB_URL | grep -o "https*://.*$"`
    elasticsearch=`heroku config --app $app | grep ELASTICSEARCH_URL | grep -o "https*://.*$"`
fi

$script $graphenedb $elasticsearch "$@"