#! /bin/bash

curl -XPUT 'http://localhost:9200/stories/'

curl -XPUT "http://localhost:9200/stories/story/_mapping" -d'
{
  "story": {
    "properties": {
      "title": {
        "type": "string",
        "store": "yes",
        "analyzer": "german"
      },
      "content": {
        "type": "string",
        "store": "no",
        "analyzer": "german"
      } 
    }
  }
}'