#! /bin/bash

echo Deleting old indices
curl -XDELETE "$1/stories"
echo .
curl -XDELETE "$1/slots"
echo .
curl -XDELETE "$1/users"
echo .

echo Set Stories
curl -XPUT "$1/stories" -d'
{
        "number_of_shards" :   1,
        "number_of_replicas" : 0
}'
echo .

echo Set Slots
curl -XPUT "$1/slots" -d'
{
        "number_of_shards" :   1,
        "number_of_replicas" : 0
}'
echo .

echo Create Stories
curl -XPUT "$1/stories/story/_mapping" -d'
{
  "story": {
    "properties": {
      "id": {
        "type": "string",
        "store": "no",
        "index": "no"
      },
      "title": {
        "type": "string",
        "store": "no",
        "analyzer": "german",
        "boost": 2.0
      },
      "content": {
        "type": "string",
        "store": "no",
        "analyzer": "german"
      },
      "created": {
        "type": "date",
        "format": "date_time",
        "store": "no",
        "index": "analyzed"
      },
      "createdBy": {
        "type": "string",
        "store": "no",
        "index": "no"
      },
      "modified": {
        "type": "date",
        "format": "date_time",
        "store": "no",
        "index": "analyzed"
      },
      "modifiedBy": {
        "type": "string",
        "store": "no",
        "index": "not_analyzed"
      },
      "due": {
        "type": "date",
        "format": "date_time",
        "store": "no",
        "index": "analyzed"
      },
      "dueTo": {
        "type": "string",
        "store": "no",
        "index": "not_analyzed"
      },
      "tags" : {
        "type": "multi_field",
        "fields": {
            "tags": {
                "type": "string",
                "analyzer" : "keyword"
            },
            "suggest": {
                "type": "completion",
                "index_analyzer": "simple",
                "search_analyzer": "simple",
                "payloads": "false"
            }
        }
      },
      "canRead": {
          "type": "string",
          "index": "not_analyzed"
      }
    }
  }
}'
echo .

echo Create Slots
curl -XPUT "$1/slots/slot/_mapping" -d'
{
  "slot": {
    "properties": {
        "name": {
            "type": "completion",
            "index_analyzer": "simple",
            "search_analyzer": "simple",
            "payloads": "false"
        }
    }
  }
}'
echo .

echo Dummy-Story
curl -XPOST "$1/stories/story/dummyxyz" -d'
{
    "id": "dummyxyz",
    "tags": [""]
}'
echo .

echo Dummy-Slot
curl -XPOST "$1/slots/slot/dummyabcde" -d'
{
    "name": ""
}'
echo .

echo Set ID
curl -XPUT "$1/users" -d'
{
        "number_of_shards" :   1,
        "number_of_replicas" : 0
}'
echo .

echo Create Users
curl -XPUT "$1/users/user/_mapping" -d'
{
  "user": {
    "properties": {
        "login": {
            "type": "completion",
            "index_analyzer": "simple",
            "search_analyzer": "simple",
            "payloads": "false"
        }
    }
  }
}'
echo .

echo Create Groups
curl -XPUT "$1/users/group/_mapping" -d'
{
  "group": {
    "properties": {
        "login": {
            "type": "completion",
            "index_analyzer": "simple",
            "search_analyzer": "simple",
            "payloads": "false"
        }
    }
  }
}'
echo .

echo Dummy-User
curl -XPOST "$1/users/user/dummyfghi" -d'
{
    "login": "_"
}'
echo .

echo Dummy-Group
curl -XPOST "$1/users/group/dummyzuio" -d'
{
    "login": "_"
}'
echo .
