#! /bin/bash


curl -X POST $1/stories/story/$2/_update -d'
{
    "doc": {
      "canRead": ["isabel"]
    }
    
}'

#curl -X POST http://localhost:8080/story/$1/access/read/$2
#curl -X POST http://localhost:8080/story/$1/access/write/$2
