#! /bin/bash
curl -X POST \
	--user hallo:welt \
	--header "Content-Type: application/json" \
	--cookie cookies.txt \
	--data '{"title": "Teststory", "content": "Testinhalt"}' \
	"http://localhost:8080/story/"
