#! /bin/bash

url="http://localhost:8080/story/$1"

echo url: $url

curl -X PUT \
	--user hallo:welt \
	--header "Content-Type: application/json" \
	--cookie cookies.txt \
	--data "{\"id\": \"$1\", \"title\": \"$2\", \"content\": \"$3\"}" \
	$url

echo 
